_target_: pytorch_lightning.Trainer

gpus: 1
num_nodes: 2
accelerator: ddp
benchmark: True
precision: 16
min_epochs: 1
max_epochs: 100
weights_summary: null
progress_bar_refresh_rate: 10
check_val_every_n_epoch: 10