_target_: src.datamodules.classifier_datamodule.ClassifierDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
dataset_name: "unlid/A"
train_val_test_split: [ 0.8, 0.1, 0.1 ]
batch_size: 8
num_workers: 5
pin_memory: True
