_target_: src.datamodules.cyclegan_csv_datamodule.CycleGanCsvDatamodule

csv_path: "E:\\tmp\\PlantCLEF2020TrainingData\\equilibrated.csv"
data_dir: ${data_dir} # data_dir is specified in config.yaml
image_size: 256
image_margin: 30
train_val_test_split: [ 0.8, 0.1, 0.1 ]
batch_size: 8
num_workers: 5
pin_memory: True
use_gpu: False
serial_batches: False